server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-direct
          uri: lb://kursnews-service
          predicates:
            - Path=/users/**
        - id: news-direct
          uri: lb://kursnews-service
          predicates:
            - Path=/news/**
        - id: users-api
          uri: lb://kursnews-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: news-api
          uri: lb://kursnews-service
          predicates:
            - Path=/api/news/**
          filters:
            - StripPrefix=1
        - id: kursnews-api
          uri: lb://kursnews-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: notifications-api
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

